spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_DATABASE}?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  error:
    whitelabel:
      enabled: false

baekmook:
  # openssl rand -hex 64
  jwt:
    secret: ${JWT_SECRET}
    access-time-ms: ${ACCESS_TOKEN_EXPIRY_MS}

  master:
    username: ${MASTER_USERNAME}
    password: ${MASTER_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: "common-local"

  datasource:
    url: jdbc:mysql://localhost:30701/SPRING?characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port:  30700

---

spring:
  config:
    activate:
      on-profile: "common-dev"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: "common-test"
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true