spring:
  datasource:
    url: jdbc:mysql://mysql:3306/SPRING?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  error:
    whitelabel:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: "common-local"

  datasource:
    url: jdbc:mysql://localhost:30701/SPRING?characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port:  30700

---

spring:
  config:
    activate:
      on-profile: "common-dev"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: "common-test"
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true